name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-unix:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fileName: frawk-x86_64-unknown-linux-gnu
          - os: macos-latest
            fileName: frawk-x86_64-apple-darwin
          - os: macos-14
            fileName: frawk-aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fileName }}
          path: target/debug/frawk

  build-on-windows:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            fileName: frawk-x86_64-windows.exe
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --no-default-features
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fileName }}
          path: target/debug/frawk.exe
