name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-unix:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fileName: zawk-x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build

  build-on-mac:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            fileName: zawk-x86_64-apple-darwin
          - os: macos-14
            fileName: zawk-aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Cache LLVM 15
        id: cache-llvm-15
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/llvm
          key: ${{ runner.os }}-llvm-15
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0.7"
          directory: ${{ runner.temp }}/llvm
      - name: Build
        run: cargo build --features llvm_backend
        env:
          LLVM_SYS_150_PREFIX: ${{ runner.temp }}/llvm

  build-on-windows:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            fileName: zawk-x86_64-windows.exe
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --no-default-features