name: Rust

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'info/**'
      - 'README.md'
      - '.gitignore'
      - 'justfile'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-linux:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fileName: zawk-x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build

  build-on-mac:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            fileName: zawk-x86_64-apple-darwin
          - os: macos-14
            fileName: zawk-aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build

  build-on-windows:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            fileName: zawk-x86_64-windows.exe
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --no-default-features