name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-unix:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            fileName: frawk-aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fileName }}
          path: target/release/${{ matrix.file }}
