name: Rust Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-unix:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fileName: zawk-x86_64-unknown-linux-gnu
          - os: macos-latest
            fileName: zawk-x86_64-apple-darwin
          - os: macos-14
            fileName: zawk-aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fileName }}
          path: target/release/zawk

  build-on-windows:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            fileName: zawk-x86_64-windows.exe
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --no-default-features
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fileName }}
          path: target/release/zawk.exe
